;//---------------------------------------------------------------------------
;//
;//	MadTracker DSP Core
;//
;//		Platforms:	All
;//		Processors:	x86
;//
;//	Copyright © 1999-2006 Yannick Delwiche. All rights reserved.
;//
;//	$Id$
;//
;//---------------------------------------------------------------------------
%define posi 0
%define posd 4
%define vol 8
%define volvar 16
%define multiplier 24
%define volvarlng 32
%define tc 36
%define sc 37
%define reverse 38
